
require('./ham.js')
//require('./monorix.js')
// require('./hexn.js')
require('./baboon.js')
// require('./timeFarm.js')
require('./boom.js')
require('./Dotcoin.js')
require('./cexp.js')
// require('./taptether.js')
//require('./blum.js')
require('./yescoin.js')
require('./wcoin.js')
require('./Dragon-king')
